kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
archiveSize: 4
mirror:
  platform:
    channels:
      - name: stable-4.20
        minVersion: "4.20.0"
        maxVersion: "4.20.4"
        shortestPath: true
      - name: stable-4.21
        minVersion: "4.21.0"
        maxVersion: "4.21.4"
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.21
      packages:
        - name: advanced-cluster-management
          channels:
            - name: release-2.16
              minVersion: "2.16.0"
              maxVersion: "2.16.0"
        - name: kiali-ossm
          channels:
            - name: stable
              minVersion: "2.17.4"
              maxVersion: "2.17.4"
        - name: servicemeshoperator
          channels:
            - name: stable
              minVersion: "2.6.14-0"
              maxVersion: "2.6.14-0"
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.21
      packages:
        - name: mongodb-enterprise
          channels:
            - name: stable
              minVersion: "1.33.0"
              maxVersion: "1.33.0"
    - catalog: registry.redhat.io/redhat/community-operator-index:v4.21
      packages:
        - name: prometheus
          channels:
            - name: beta
              minVersion: "0.56.3"
              maxVersion: "0.56.3"
  additionalImages:
    - name: registry.redhat.io/ubi9/ubi:latest
    - name: registry.redhat.io/openshift4/ose-cli:latest
    - name: registry.redhat.io/openshift4/ose-installer:latest
  helm:
    repositories:
      - name: redhat-helm-charts
        url: https://charts.openshift.io